source :rubygems
gem 'sinatra'
gem 'thin', '1.5.0'
gem 'haml'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rack-flash3'
gem 'sinatra-authentication', :git => 'https://github.com/timmillwood/sinatra-authentication.git'
gem 'sanitize'
gem 'pony'
gem 'builder'
gem 'newrelic_rpm'
