source :rubygems
gem 'sinatra'
gem 'thin', '1.5.0'
gem 'haml'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-postgres-adapter'
gem 'rack-flash3'
gem 'sinatra-authentication', :git => 'git://github.com/timmillwood/sinatra-authentication.git'
gem 'sanitize'
